# Generated by Django 5.0.2 on 2024-02-18 10:03

import django.db.models.deletion
import email_automation.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=email_automation.constants.BatchStatus.choices, default='PENDING', max_length=100),
        ),
        migrations.AddField(
            model_name='email',
            name='status',
            field=models.CharField(choices=email_automation.constants.EmailStatus.choices, default='PENDING', max_length=100),
        ),
        migrations.AlterField(
            model_name='email',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='email_automation.batch'),
        ),
    ]
